#kubectl create ns dev
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
# Deployment  #ReplicaSet #ReplicationController 
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: dr1
  labels:
    app: django
    env: dev
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: d1
      labels:
        app: django
        env: dev
    spec:
      containers:
      - name: django
        image: devopsjuly22017/django-web:latest
        ports:
        - containerPort: 8000


#kubectl run d1 --image=devopsjuly22017/django-web --port=8000 -n dev
# apiVersion: v1
# kind: Pod
# metadata:
#   name: d1
#   labels:
#     app: django
#     env: dev
#   namespace: dev 
# spec:
#   containers:
#   - name: django
#     image: devopsjuly22017/django-web:latest
#     ports:
#     - containerPort: 8000

#kubectl expose pod d1 --port=8000 --target-port=8000 --name=d1svc --type=NodePort -n dev
---
apiVersion: v1
kind: Service
metadata:
  name: d1svc
  namespace: dev
spec:
  selector:
    app: django
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: dev
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: d1svc
            port:
              number: 8000

