#kubectl create ns dev
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
#kubectl run d1 --image=devopsjuly22017/django-web --port=8000 -n dev
apiVersion: v1
kind: Pod
metadata:
  name: d1
  labels:
    app: django
    env: dev
  namespace: dev 
spec:
  containers:
  - name: django
    image: devopsjuly22017/django-web:latest
    ports:
    - containerPort: 8000

#kubectl expose pod d1 --port=8000 --target-port=8000 --name=d1svc --type=NodePort -n dev
---
apiVersion: v1
kind: Service
metadata:
  name: d1svc
  namespace: dev
spec:
  selector:
    app: django
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

