pipeline {
    agent { label 'k8s-label' }

    stages {
         stage('clone') {
            steps {
                 checkout scm  
                  echo "build"
            }
        }
        stage('Build') {
            steps {
                 dir('django') {
                    echo "build"
                    sh "docker build -t devopsjuly22017/django-web ."
                    sh "docker push devopsjuly22017/django-web:latest"
                 }
            }
        }
         stage('deploy') {
            steps {
                  echo "deploy"
                  dir('django/k8s') {
                    sh "kubectl delete -f django.yml"
                    sh "kubectl apply -f django.yml"
                  }
            }
        }
    }
}
