pipeline {
    agent { label 'maven-label' }

    tools {
        maven "maven-3.6.2"
    }

    stages {
        stage('Build') {
            steps {
                 checkout scm
              
                sh "mvn -Dmaven.test.failure.ignore=true clean package"
            }
        }
    }
}
