pipeline {
    agent { label 'k8s-label' }

    stages {
         stage('clone') {
            steps {
                 checkout scm  
                  echo "build"
            }
        }
        stage('Build') {
            steps {
                 
                  echo "build"
            }
        }
         stage('deploy') {
            steps {
                  echo "deploy"
                  sh "kubectl apply -f django/k8s/django.yml"
            }
        }
    }
}
